# grafana-agent-config.yaml
server:
  log_level: debug

metrics:
  global:
    scrape_interval: 15s
    remote_write:
      - url: http://envoy:8080/api/v1/receive
        basic_auth:
          username: tenant1
          password: password123

  configs:
    - name: default
      scrape_configs:
        # Docker container metrics
        - job_name: docker
          docker_sd_configs:
            - host: unix:///var/run/docker.sock
              refresh_interval: 15s
          relabel_configs:
            - source_labels: ['__meta_docker_container_name']
              target_label: container_name
            - source_labels: ['__meta_docker_container_id']
              target_label: container_id

logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      # Docker container logs
      - job_name: docker
        docker_sd_configs:
          - host: unix:///var/run/docker.sock
            refresh_interval: 15s
        relabel_configs:
          - source_labels: ['__meta_docker_container_name']
            target_label: container_name
          - source_labels: ['__meta_docker_container_id']
            target_label: container_id
            
    clients:
      - url: http://envoy:8080/loki/api/v1/push
        basic_auth:
          username: tenant1
          password: password123
        tenant_id: tenant1_id
        batchwait: 1s
        batchsize: 1048576